// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lymeenucexbtzctkdnmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bWVlbnVjZXhidHpjdGtkbm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTMxOTYsImV4cCI6MjA2NDgyOTE5Nn0.b-88-7wwHyHNe38Gy1vMz-UECn5kZTxMA-gjWF-E8fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);